### ISSUE TITLE
Automatically match mods

### ISSUE THREAD

**Issue by freezy** [freezy/node-vpdb#63]
Since we went through all the vpt hashing shit anyway, we can now strip down vpt/vpx files into chunks, hash them and check how many chunks match already existing chunks.

That means if a table file is uploaded, we can calculate a percentage of other files with the same chunks. The percentage can be either by number of matched chunks or size of matched chunks (or both).

The goal is to detect mods and check if the original's licenses matches when the author differs (see also #64). If so, we could keep the release under moderation until the original author gives then green light.

The structure of a chunk looks like this:

```javascript
{ 
  hash: 0x208e4a5ad7ddf1fd667c67a289645718,
  bytes: 17305,
  type: 'image',
  meta: {
    stream: 'Image0',
    name: 'plungerwhitetip',
    path: 'E:\\Models\\plungerwhitetip.png',
    width: 32,
    height: 256 
  } 
},
```

A resource, such as `/files/{file_id}/blockmatch` would then retrieve all other files with common blocks and return it similar to this:

```json
{
  "file": {
    "id": "pkzsu8nze",
    "name": "Medieval-Madness_VP91x_2.4.3FS.vpt",
    "url": "http://localhost:3000/storage/v1/files/pkzsu8nze.vpt",
    "bytes": 46915584,
    "variations": {},
    "is_protected": true,
    "counter": {
      "downloads": 0
    },
    "cost": 1
  },
  "matches": [
    {
      "file": {
        "id": "pkyvccaze",
        "name": "Medieval-Madness_VP91x_2.3.2FS.vpt",
        "url": "http://localhost:3000/storage/v1/files/pkyvccaze.vpt",
        "bytes": 16125952,
        "variations": {},
        "is_protected": true,
        "counter": {
          "downloads": 0
        },
        "cost": 1
      },
      "matchedCount": 522,
      "matchedBytes": 1582971,
      "countPercentage": 29.794520547945208,
      "bytesPercentage": 3.5085377275008685
    },
    {
      "file": {
        "id": "e2zzqcgyp",
        "name": "VP10_Medieval_Madness_Dozer_RTM_1.3.vpx",
        "url": "http://localhost:3000/storage/v1/files/e2zzqcgyp.vpx",
        "bytes": 132423680,
        "variations": {},
        "is_protected": true,
        "counter": {
          "downloads": 0
        },
        "cost": 1
      },
      "matchedCount": 72,
      "matchedBytes": 18163299,
      "countPercentage": 4.10958904109589,
      "bytesPercentage": 40.25760408584793
    }
  ]
}
```
This is a real-world example with only 4 games in the database. We could break it down into more detailed information like images, sounds, game objects etc.

The good thing is that we can adapt the retrieval algorithm easily without the need to migrate data.

### Tasks:

- [x] Parse blocks and hash them somewhat intelligently (i.e. hash the image data but not the name of the texture)
- [x] Do analysis and save hashes to the database on table file upload
- [x] Add a resource for retrieving the match data (currently at `/files/{file_id}/blockmatch`)
- [x] Clean up table blocks when file is deleted
- [x] Add API documentation
- [x] Add tests
- [x] Play with more data and thresholds in order to avoid insignificant matches
- [x] Add option to exclude matches of the same release since they are likely to be similar anyway (or make it the default option)
